Update deploy-prod.yml

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -49,7 +49,7 @@ jobs:
         run: |
           echo "Running tests..."
           echo "This step will intentionally fail to test notifications."
-          exit 0 # This causes the step to fail
+          exit 1 # This causes the step to fail
           echo "Tests successful!" # This line will not be reached
 
       - name: Notify on Failure
